const express = require('express')
const router = express.Router()
const {getRecords,countRecords,createRecord,deleteRecord,updateRecord,countToday,deleteAll,getMyRecords,getPresentToday,getMonthPrence,MyRecords,getTodayOnTime,getTodayLate,getRecordDataCollection,getRecordDataCollectionTime,getRecordDataCollectionLate} = require('../controllers/recordController.js')

router.get('/',getRecords)
router.get('/count',countRecords)
router.get('/countToday',countToday)
router.post('/create/:id',createRecord)
router.delete('/delete/:id',deleteRecord)
router.put('/update/:id',updateRecord)
router.delete('/deleteAll',deleteAll)
router.get('/myrecords/:id',getMyRecords)
router.get('/presentToday/:id',getPresentToday)
router.get('/getMonthPresence/:id',getMonthPrence)
router.get('/my/:id',MyRecords)
router.get('/countTodayOnTime',getTodayOnTime)
router.get('/countTodayLate',getTodayLate)
router.get('/dataCollection',getRecordDataCollection)
router.get('/dataCollectionTime',getRecordDataCollectionTime)
router.get('/dataCollectionLate',getRecordDataCollectionLate)
module.exports = router